### ISSUE TITLE
Validation for presence of loading bar

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyDePaul#2]
Make sure only one loading bar can be visible at a time

**Comment by SergueiFedorov** [comment]
Does this happen if they keep clicking on the on the professor's name while the loading bar is showing?

**Comment by ochagata** [comment]
Yeah, if you keep clicking, it keeps generating more

**Comment by SergueiFedorov** [comment]
I can fix that really quick...

**Comment by ochagata** [comment]
![image](https://cloud.githubusercontent.com/assets/4699540/6858092/d50cf648-d3d9-11e4-9673-d41d0e5bd488.png)

**Comment by ochagata** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4699540/6858102/e1f2e91c-d3d9-11e4-95c5-4d4ffed447d6.png)

**Comment by SergueiFedorov** [comment]
Fixed
