### ISSUE TITLE
Make it so that the popups disappear once the professor name is no longer present

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyDePaul#8]
![image](https://cloud.githubusercontent.com/assets/4699540/6858233/e0506cc8-d3da-11e4-88f2-ae5e93780b8f.png)

**Comment by SergueiFedorov** [comment]
Can we solve this using an X in the corner to close it? Or should it disappear once you navigate somewhere else?

**Comment by ochagata** [comment]
I'd say both, that lets them remove the box when they don't need it, and if they navigate away from the search page they wont really need it anyways

**Comment by SergueiFedorov** [comment]
Hmmm... I am wondering how we can do that. Considering that it's not possible (at least we haven't gotten it to work) to detect if the page has navigated or not

**Comment by SergueiFedorov** [comment]
Popup will now disappear if you leave the search results page or the professors name is no longer there.
